import os
import re
import math
import shutil
import logging
import sys
from pathlib import Path
from typing import Optional


def convert_to_SI_units(value: float) -> float:
    """Convert ADDA's output to SI units (m²)"""
    return value * 1e-12


def compute_rel_err(
    val1: Optional[float], val2: Optional[float]
) -> Optional[float]:
    if val1 and val2:
        return abs(val1 - val2) / abs(val2)
    else:
        return None


def matching_digits_from_rel_err(rel_err: Optional[float]) -> Optional[int]:
    if rel_err:
        return int(-math.log10(rel_err))
    else:
        return None


def clean_output_files():
    """Remove ADDA and IFDDA output files and folders."""
    for path in Path(".").glob("run*"):
        if path.is_dir():
            shutil.rmtree(path)
    for fname in ["ExpCount", "inputmatlab.mat", "filenameh5", "ifdda.h5"]:
        if os.path.exists(fname):
            os.remove(fname)


def find_adda_internal_field(pair_index: int) -> Optional[str]:
    """
    Find the internal field file generated by ADDA (run* folders)
    for a given index.
    """
    pattern = f"run{pair_index:03d}_*/IntField-Y"
    for path in Path(".").glob(pattern):
        if path.exists():
            return str(path)
    return None


def extract_eps_from_adda(
    line: str, line_id: int, logger: logging.Logger
) -> int:
    """Extract the -eps value from an ADDA command line. Exit if not found."""
    match = re.search(r"-eps\s+(\d+)", line)
    if not match:
        logger.error(f"Missing -eps argument in ADDA command line: {line_id}")
        sys.exit(1)
    return int(match.group(1))
